### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by boki69** [elecard-med/redpoll#1]
Hi,

A tried your plugin on redmine 3.3.3, but I have two errors.

**If I vote for a question:**

Production log:

> Processing by RedpollVotesController#vote as HTML
>   Parameters: {"utf8"=>"✓", "authenticity_token"=>"", "redpoll_vote"=>{"user_id"=>"1", "poll_result"=>{"1"=>"2"}}, "commit"=>"vote", "redpoll_poll_id"=>"1"}
>   Current user: admin (id=1)
> 
> Completed 500 Internal Server Error in 294ms (ActiveRecord: 282.1ms)
> 
> ActiveRecord::StatementInvalid (Mysql2::Error: Data too long for column 'cookie' at row 1: INSERT INTO `redpoll_votes` (`cookie`, `user_id`, `redpoll_variant_id`)
>  plugins/redpoll/app/models/redpoll_vote.rb:11:in `block in mass_create'
>   plugins/redpoll/app/models/redpoll_vote.rb:10:in `each'
>   plugins/redpoll/app/models/redpoll_vote.rb:10:in `mass_create'
>   plugins/redpoll/app/controllers/redpoll_votes_controller.rb:27:in `vote'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**If I try to get the result of a poll:**

Production log:

> Processing by RedpollVotesController#adminresult as HTML
>   Parameters: {"redpoll_poll_id"=>"1"}
>   Current user: admin (id=1)
> Completed 500 Internal Server Error in 224ms (ActiveRecord: 196.7ms)
> 
> TypeError (String can't be coerced into Float):
>   plugins/redpoll/app/helpers/redpoll_votes_helper.rb:47:in `+'
>   plugins/redpoll/app/helpers/redpoll_votes_helper.rb:47:in `block (2 levels) in adjust_percentage'
>   plugins/redpoll/app/helpers/redpoll_votes_helper.rb:46:in `each'
>   plugins/redpoll/app/helpers/redpoll_votes_helper.rb:46:in `block in adjust_percentage'
>   plugins/redpoll/app/helpers/redpoll_votes_helper.rb:43:in `each'
>   plugins/redpoll/app/helpers/redpoll_votes_helper.rb:43:in `adjust_percentage'
>   plugins/redpoll/app/helpers/redpoll_votes_helper.rb:40:in `analize_redpoll'
>   plugins/redpoll/app/controllers/redpoll_votes_controller.rb:60:in `adminresult'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
> 
> 

Redmine info:

>  Environment:
>   Redmine version                3.3.3.stable.16559
>   Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
>   Rails version                  4.2.7.1
>   Environment                    production
>   Database adapter               Mysql2
> SCM:
>   Subversion                     1.9.3
>   Mercurial                      3.7.3
>   Git                            2.7.4
>   Filesystem                     
> Redmine plugins:
>   redmine_banner                 0.1.2-dev
>   redmine_ckeditor               1.1.4
>   redmine_custom_css             0.1.6
>   redmine_custom_js              0.1.0
>   redmine_custom_workflows       0.1.6
>   redmine_default_assign         0.6
>   redmine_didyoumean             1.2.0
>   redmine_issue_templates        0.1.5
>   redmine_ldap_sync              2.0.8.devel.gf916e6574e
>   redmine_lightbox2              0.3.2
>   redmine_logs                   0.1.0
>   redmine_per_project_formatting 0.0.4
>   redmine_spent_time             3.1.2
>   redmine_theme_changer          0.2.0
>   redmine_wiki_extensions        0.7.0
>   redmine_work_time              0.3.4
>   redpoll                        0.0.1
>   sidebar_hide                   0.0.8
>   tracker_hider                  0.1.0

Best regards.

**Comment by elecard-med** [comment]
We used the string type for the cookie but it is not correct because in mysql it is converted into VARCHAR (255) and the cookie length is greater than 255. In the nearest future we will write migrate.

https://stackoverflow.com/questions/3354330/difference-between-string-and-text-in-rails

**Comment by boki69** [comment]
I've tested it and everything is ok!

Thanks!

**Comment by ziogun** [comment]
Hi, 
I've just installed your plugin on redmine 3.3.3 and paste "{{redpoll(70%, 300px, 1)}}" into wiki page after create polls but the URL is changed into "//localhost/redpoll_votes/1" so I can't see the voting page on wiki.
If I just paste the URL "http://localhost/redmine/redpoll_votes/1" into chrome address input box, it works.

Best regards.
