### ISSUE TITLE
"{{redpoll(70%, 300px, 1)}}" doesn't work.

### ISSUE THREAD

**Issue by ghost** [elecard-med/redpoll#2]
Hi, 
I've just installed your plugin on redmine 3.3.3 and paste "{{redpoll(70%, 300px, 1)}}" into wiki page after creating polls but the URL is changed into "//localhost/redpoll_votes/1" so I can't see the voting page on wiki.
If I just paste the URL "http://localhost/redmine/redpoll_votes/1" into chrome address input box, it works.

Best regards.

**Comment by elecard-med** [comment]
The problem is with the formation of URL for iframe. We'll fix this.

 Thanks for the feedback
